### ISSUE TITLE
Change Detection

### ISSUE THREAD

**Issue by arielcessario** [ngbaires/ng-baires#3]
### Título
Change Detection

### Descripción
Explicar que es change detection, como funciona en Angular 2, primeramente estaba pensando en un acercamiento básico, pero también podemos definir la dificultad de acuerdo a lo que crean que los asistentes pueden necesitar.

### Sobre el orador
**Slack**: ariel.cessario 

**Twitter:** usuario de Twitter (si tenés)

**Sitio:** url del sitio personal (si tenés)

### Recursos
**Slides de la presentación:** url de los slides de la presentación (si tenés)

**Repositorio de la charla:** url del repositorio con el código de la charla (si tenés)

### Extra
Tenes la charla preparada?
No
En qué mes la podrías dar?
A partir de mediados de Marzo

Avisanos si necesitas algo especial para poder dar la charla así lo podemos planificar con tiempo.

Tenes alguna idea y necesitas ayuda para moldearla, contactamos.

**Comment by jorgeucano** [comment]
Hola @arielcessario me encanta!!
Si tenes alguna duda/cambio contactanos pero ya te tenemos en cuenta para marzo/abril :) 
Creo que un incial/intermedio seria un golazo

**Comment by arielcessario** [comment]
Excelente!! Lo voy preparando y en cuanto tenga algo ya se los paso. Gracias y abrazo!

**Comment by jorgeucano** [comment]
gracias a vos por querer compartir =) estamos en contacto!

**Comment by AndresCenci** [comment]
Ariel nos pasó el documento inicial de su tema elegido para que vayamos viendo y opinemos. Mientras va a ir haciendo la presentación.
 
[Presentación - Contenido.docx](https://github.com/ngbaires/ng-baires/files/1800074/Presentacion.-.Contenido.docx)

**Comment by jorgeucano** [comment]
@arielcessario estas para abril ?

**Comment by arielcessario** [comment]
Jorge, buenas!

Solo tengo complicado en abril desde el 12 al 15, el resto puedo sin problemas. No se que fechas tenían planeadas.

La presentación la estaría pasando la semana que viene así vamos revisando.

**Comment by arielcessario** [comment]
Buenas a todos,

Les paso el link de la presentación, perdón por la demora. 

https://docs.google.com/presentation/d/1u8Umr8L-JhpLh6ZPcftPc5Bqf0pFXwHWok6uFCpzz_w/edit?usp=sharing

Cualquier cosa que vean para modificar o corregir, no duden en avisarme.

Voy a estar haciendo algunos retoques finales, así que puede ir cambiando, pero no creo que mucho, solo algunos textos.

Saludos!!
