### ISSUE TITLE
Angular CLI para varios builds

### ISSUE THREAD

**Issue by ariasfernando** [ngbaires/ng-baires#5]
### Título
Buildeando Angular CLI como un campeón (?)

### Descripción
Tuve que configurar el build de un proyecto en Angular para varias apps que reutilizaban los recursos existentes y sólo cambiaban algunos assets o variables, y para eso tuve que investigar y pelearme un poco con el CLI. De esa experiencia saqué algunas conclusiones personales sobre el uso, experiencias, decisiones que hacen que pueda optimizar el build en este tipo de casos.

### Sobre el orador
**Slack**: @fercieguno

**Twitter:** @fercieguno

### Extra
No tengo la charla preparada, de hecho tengo algunos puntos que investigar antes de llegar a las conclusiones para tener un panorama global. Sí tengo la idea general y algunas decisiones ya tomadas que pueden servir de experiencia.

En qué mes la podrías dar?
A partir de abril.

**Comment by jorgeucano** [comment]
WOW 👏  me encanta esta futura charla!! 
El CLI es algo super interesante y mas lo que tuviste que hacer!!
@ariasfernando te contamos para abril entonces :) 
Cualquier cambio/duda nos podes contactar !!

Saludos y exito con este proyecto

**Comment by jorgeucano** [comment]
@ariasfernando te confirmo para Julio, te paso los detalles por privado :D

**Comment by jorgeucano** [comment]
muchas gracias por la charla estuvo genial
