### ISSUE TITLE
Migrando de angular.js a Angular

### ISSUE THREAD

**Issue by josuerios** [ngbaires/ng-baires#7]
### Título
Migrando de angular.js a Angular

### Descripción
Proceso de decisión y migración de angular.js a Angular, valorando otras herramientas como React y Vue

### Sobre el orador
**Slack**:  Josue Rios
**Twitter:** @jdriosdiaz

### Extra
Tenes la charla preparada?
Tengo algo pequeño armado

**Comment by jorgeucano** [comment]
confirmado para julio, ahora te envio mas detalles por privado

**Comment by jorgeucano** [comment]
estuvo increible, muchas gracias :D
